### ISSUE TITLE
Using different model with this pipeline

### ISSUE THREAD

**Issue by Windson9** [NVIDIA-ISAAC-ROS/isaac_ros_object_detection#11]
Hello.

I have a trained YOLO model which I want to run using this object detection pipeline for ROS application. My question is:

1. Is it possible to run any other models using this pipeline
2. If yes, what changes do I need to make in encoder, triton node and decoder file
3. Do I need to make any changes from Nitros side or Nitros is generic for any running models

**Also, Why this detectnetV2 model is not possible to run on TensorRT ?**

Thanks in advance.
Mayank

**Comment by hemalshahNV** [comment]
`isaac_ros_detectnet` package within Isaac ROS Object Detection is meant only to run DetectNetV2-architecture models and is not compatible with YOLO. You can use the `isaac_ros_tensor_rt` package (or `isaac_ros_triton` package) from Isaac ROS DNN Inference and write your own YOLO decoder however. `isaac_ros_dnn_image_encoder` for preprocessing will likely work as-is.

DetectnetV2 requires implicit batch dimensions which is supported by TensorRT through `isaac_ros_triton` but not `isaac_ros_tensor_rt`.

**Comment by Windson9** [comment]
One last query. 

In any ROS AI packages, we are converting the raw image format into tensorlist using encoders for the Triton server/TenosrRT to run the inference and then converting it back to visualize using Decoders. 

If I want to deploy any engine/plan file on either TensorRT Runtine or Triton server. Does the model still expects tensorlist ? Meaning, do I still need to use encoders and decoders if I am not using ROS at all ?

Sorry for all the questions. I am new to this. Thanks for your quick reply.
Mayank

**Comment by hemalshahNV** [comment]
The inference engine (TensorRT, Triton, etc.) loads a model (structured bag of weights). You will need to pre-process/convert/encode your inputs into a blob of numbers (tensors) that the inference engine can use to determine a model's output. You will then likely need to post-process the output of the model to yield a usable result for the rest of your system.

With Isaac ROS, we provide a ROS2 package called `isaac_ros_dnn_encoders` which provides a node that can take in a sensor_msgs::Image ROS message and yield a TensorList ROS message. The TensorList is then sent to the inference node which uses the named bags of numbers as inputs for running inference on a model with either TensorRT or Triton. The decoders, like `isaac_ros_detectnet` then interpret the output of the model which is another tensor and converts them into bounding boxes after some filtering/post-processing.

If you do not want to use ROS at all, you can use the Triton through the Triton Inference Server which provides a gRPC interface or link against TensorRT directly. You would have to implement your own pre-processing/encoding code to handle whatever your input format is and then implement your own post-processing/decoding code to handle the output of the model architecture you're running inference on. If it is a DetectNetV2 architecture model, you have the schema or structure of what the bags of numbers and their named endpoints look like.

Perhaps you could describe your use case more? If you're not planning on using ROS, then this package may not be of as much use to you. I suggest you consider NVIDIA [Deepstream SDK](https://developer.nvidia.com/deepstream-sdk) which may be more helpful.

If you're looking for resources to learn more about deep learning, take a look at NVIDIA's [Deep Learning Institute](https://www.nvidia.com/en-us/training/) to get a better idea of how it all works.

**Comment by Windson9** [comment]
My use case is that I have a trained model which I want to deploy on ROS using this pipeline but it is not DetectnetV2 architecture.   As mentioned in your first answer, the encoder and the inference platform will remain the same (I noticed that for image segmentation also you are providing the same `isaac_ros_dnn_inference`)

**Comment by jaiveersinghNV** [comment]
Yes, you can write your own ROS2 decoder node to support inference with different models.

The output of the Isaac ROS inference nodes will be of the type [`isaac_ros_tensor_list_interfaces/TensorList`](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_common/blob/main/isaac_ros_tensor_list_interfaces/msg/TensorList.msg). This message will have an identical schema to the direct output of your model architecture.

For example, if your model architecture outputs a tensor of dimensions (1, 3, 64, 64), then the corresponding `TensorList` message will have 1 `Tensor` with a `TensorShape` of those exact dimensions.

Your decoder node will then need to receive as input a `TensorList` ROS message and parse the fields in a way that makes sense given your model architecture.

**Comment by Windson9** [comment]
Thanks a lot for all the answers. Closing this issue now.
