### ISSUE TITLE
detections topic -- no time listed in header

### ISSUE THREAD

**Issue by eladpar** [NVIDIA-ISAAC-ROS/isaac_ros_object_detection#15]
hey i've been trying to measure the fps of the detentions 
and there is no time in the header of the topic /detectnet/detections:
![Screenshot from 2022-11-21 17-23-34](https://user-images.githubusercontent.com/53909719/203093398-7dfd545e-4c16-4906-bed2-c24ef3957c20.png)

**Comment by hemalshahNV** [comment]
isaac_ros_detectnet package forwards timestamps from the inputs for its output messages. Please check the timestamps of your inputs to make sure they are filled in correctly.

**Comment by eladpar** [comment]
That was the problem :) thanks!
