### ISSUE TITLE
Could NOT find CUDA (missing: CUDA_INCLUDE_DIRS) (found version "11.4")

### ISSUE THREAD

**Issue by thanujTa** [NVIDIA-ISAAC-ROS/isaac_ros_object_detection#17]
admin@thesis-desktop:/workspaces/isaac_ros-dev$ cd /workspaces/isaac_ros-dev && \
>   colcon build --symlink-install && \
>   source install/setup.bash

error:
Starting >>> isaac_ros_test
Starting >>> isaac_ros_tensor_list_interfaces 
Finished <<< isaac_ros_test [9.12s]                                                                 
Starting >>> isaac_ros_nitros                                          
--- stderr: isaac_ros_nitros                                                                
CMake Error at /usr/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find CUDA (missing: CUDA_INCLUDE_DIRS) (found version "11.4")
Call Stack (most recent call first):
  /usr/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.23/Modules/FindCUDA.cmake:1264 (find_package_handle_standard_args)
  CMakeLists.txt:67 (find_package)

---
Failed   <<< isaac_ros_nitros [15.5s, exited with code 1]
Aborted  <<< isaac_ros_tensor_list_interfaces [50.3s]                                   

Summary: 1 package finished [51.8s]
  1 package failed: isaac_ros_nitros
  1 package aborted: isaac_ros_tensor_list_interfaces
  1 package had stderr output: isaac_ros_nitros
  18 packages not processed

is there any mistake in my installations? please let me know

Thanks

**Comment by hemalshahNV** [comment]
Just to confirm, this is within the Isaac ROS Dev base containers (not directly on host) and on a Jetson or x86_64? The missing include dirs could be that you have CUDA 11.4 runtime installed but not the CUDA 11.4 toolkit (which includes the development headers and move). Could you post a listing of what's in `/usr/local/cuda` and the output of `env | grep CUDA`?

**Comment by thanujTa** [comment]
hello,

I'm not getting anykind of output if i type in the command
env | grep CUDA

**Comment by hemalshahNV** [comment]
Have you installed the CUDA Toolkit on this machine (not just the CUDA runtime)? Judging from your console output, it looks like you are on bare metal (no Docker) on an x86_64 machine. What is the output of `nvidia-smi` to make sure we have a compatible GPU installed?
