### ISSUE TITLE
Huge gxf_log file fills disc space

### ISSUE THREAD

**Issue by GEngels** [NVIDIA-ISAAC-ROS/isaac_ros_object_detection#20]
When running the human detector for a couple days in a row, it will at some point crash because there is not enough disc space on my NVIDIA jetson. This is because Isaac Ros write a huger log file named gxf_log in /tmp. I have been looking for option to disable the logging but haven't found it. 

Currently we made some additions so the file gets deleted but we would prefer an option to just turn it off. Are you aware of this logging?

**Comment by jaiveersinghNV** [comment]
Could you please provide some additional details about your system? Which specific Jetson board are you running on? What is the specific error thrown when the node crashes?

**Comment by jaiveersinghNV** [comment]
Thanks for the extra details. We are looking into this.

**Comment by jaiveersinghNV** [comment]
Could you please try running this again on the latest [Isaac ROS DP3 Release](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_object_detection/releases/tag/v0.30.0-dp)?

The newest release should no longer log to that file.
