### ISSUE TITLE
isaac_ros_common/scripts/run_dev.sh your_ws failed

### ISSUE THREAD

**Issue by beyondli** [NVIDIA-ISAAC-ROS/isaac_ros_object_detection#4]
Hi expert,
I I try to test  isaac_ros_common/scripts/run_dev.sh your_ws [on]([url](url)) xavier AGX with sys 4.6.1 followed guide , during run command : errors report 
you can check log in attachments ,thanks!

Collecting protobuf<=3.20.1,>=3.12.2 (from onnx)
  Downloading https://files.pythonhosted.org/packages/c6/1c/f18d97fc479b4fb6f72bbb0e41188575362e3bbd31014cf294ef0fdec8bf/protobuf-3.19.4-py2.py3-none-any.whl (162kB)
Building wheels for collected packages: onnx
  Running setup.py bdist_wheel for onnx: started
[91m  Failed building wheel for onnx
[0m  Running setup.py bdist_wheel for onnx: finished with status 'error'
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-hofm4dj7/onnx/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpdbtxuctapip-wheel- --python-tag cp36:
  fatal: not a git repository (or any of the parent directories): .git
  /usr/local/lib/python3.6/dist-packages/setuptools/installer.py:30: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
    SetuptoolsDeprecationWarning,
  running bdist_wheel
  r
[test.txt](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_object_detection/files/9002077/test.txt)

**Comment by kajanan-nvidia** [comment]
Hello,

I would recommend trying to use Isaac ROS Developer Preview (based on ROS2 Humble), and seeing if the problem persists.

If you need to stay on ROS2 Foxy, a user reported a potential fix here: https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_common/issues/25#issuecomment-1149529853 that may be worth checking out.
