### ISSUE TITLE
isaac_ros_object_detection node doesn't install parameters file

### ISSUE THREAD

**Issue by Tristis116** [NVIDIA-ISAAC-ROS/isaac_ros_object_detection#8]
This line installs the launch file but does not install the parameters file.
https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_object_detection/blob/237774a6a2fea4d72f0608b300a5d5149fc1ee07/isaac_ros_detectnet/CMakeLists.txt#L83
So a user has to use symlink build to launch the node or to copy the file himself.

`ament_auto_package(INSTALL_TO_SHARE launch params)`
solves the issue

**Comment by hemalshahNV** [comment]
This is a great catch. Thanks for the fix! This didn't make it into DP1.1 but we'll consider this for a hotfix.

**Comment by hemalshahNV** [comment]
Fixed in an update. Thanks again!
